# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='environments.Environment'),
            preserve_default=False,
        ),
    ]
